---
title: "minsu"
author: "Siming Yan"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
train <- read.csv("./train_data.csv")
target <- read.csv("./target.csv")
```

```{r cars}
head(train)
# train['X18']
# train['X88'] = lapply(train['X18'], FUN = substr, start = 1, stop = 5)
# train = train[,! names(train) %in% 'X18']
# train = train[,! names(train) %in% 'X18']

```

```{r}
# View(train)
```

# all fast dummies

```{r}
# df_train = fastDummies::dummy_columns(train, select_columns = c("X13", "X24", "X88", "X8", "X9"))
# is.na(df_train)
```

# no fast dummies

```{r}
train = train[,! names(train) %in% c('X18', 'X21', 'X22', 'X23')]
df_train = train
df_train = df_train[ , !names(df_train) %in% c("X13")]
# str(lapply(df_train, class)) # 8 9 24
df_train$X8  = as.factor(df_train$X8)
df_train$X9  = as.factor(df_train$X9)
df_train$X24 = as.factor(df_train$X24)
levels(df_train$X8)  = c(0,1)
levels(df_train$X9)  = c(0,1)
levels(df_train$X24) = c(0,1)
# dim(df_train)
cat_col = c(3, 5, 6, 7, 8, 9, 10, 15, 17)
cat_col = lapply("X", paste0, cat_col)[[1]]
cat_col = strsplit(cat_col, " ")
cat_col %>% as.array()
# names(df_train)
df_train = fastDummies::dummy_columns(df_train, select_columns = cat_col)
# str(df_train)
# target[,1]

```

```{r}
# depracate
# library(AppliedPredictiveModeling)
# pp_hpc <- preProcess(df_train, 
#                      method = c("center", "scale", "YeoJohnson"))
# transformed <- predict(pp_hpc, newdata = df_train)
write.csv(df_train, "./fin_train.csv", row.names = F)
```

```{r}
library(xgboost)
library(caret)
1+1
```


```{r}
library(doParallel)
cl <- makePSOCKcluster(8)
registerDoParallel(cl)
# stopCluster(cl)
```

 
```{r}
trControl = trainControl(
    method = 'cv',
    number = 10)
```

```{r}
tuneGridXGB = expand.grid(
    nrounds = c(300, 500),
    max_depth = c(4,6,9,13),
    eta = c(0.05, 0.1),
    # lambda = c(.01, .1),
    # alpha = c(.01, .1)
    gamma = .1,
    min_child_weight = c(25),
    colsample_bytree = c(1),
    subsample = c(1)
    )
# which(is.na(target[,1]) == T)
```


```{r}
start <- Sys.time()

xgbmod_2 <- train(
    x = transformed,
    y = target[,1],
    method = 'xgbTree',
    metric = "RMSE",
    trControl = trControl,
    tuneGrid = tuneGridXGB,
    verbose = T)

print(Sys.time() - start)
# xgbmod_2
```

```{r}
lr_md = train(x = transformed,
    y = target[,1],
    method = "penalized",
    metric = "RMSE",
    lambda1 = .1,
    lambda2 = .1,
    verbose = T) 
# 
# rf_md = train(x = transformed,
#     y = target[,1],
#     method = "ranger",
#     metric = "RMSE",
#     mtrees = c(200, 400, 600),
#     verbose = T) 
# 1+1
```

```{r}
 
```

```{r}
preds <- predict(xgbmod_2, newdata = test_my, type = "prob")
sub2$Pred = preds$yes
sub2 = sub2[,1:2]
# sub2
write.csv(sub2, "./sub_stg2.csv", row.names = F)
```


```{r}
train_data_my_stg2 = cbind(train_data_my, train_label_my)
# train_label_my
# write.csv(train_data_my_stg2 , "./sb/train_w_stg2.csv", row.names = F)
# write.csv(test_my , "./sb/test_w_stg2.csv", row.names = F)
```

#--------------------------------------------
```{r}
# testdata
 
test = read.csv("./test_data.csv")
```

```{r}
test = test[,! names(test) %in% c('X18', 'X21', 'X22', 'X23')]
df_test = test
df_test = df_test[ , !names(df_test) %in% c("X13")]
# str(lapply(df_test, class)) # 8 9 24
df_test$X8  = as.factor(df_test$X8)
df_test$X9  = as.factor(df_test$X9)
df_test$X24 = as.factor(df_test$X24)
levels(df_test$X8)  = c(0,1)
levels(df_test$X9)  = c(0,1)
levels(df_test$X24) = c(0,1)
names(df_test)
cat_col = c(3, 5, 6, 7, 8, 9, 10, 15, 17)
cat_col = lapply("X", paste0, cat_col)[[1]]

df_test = fastDummies::dummy_columns(df_test, select_columns = cat_col)

# library(AppliedPredictiveModeling)
# pp_hpc2 <- preProcess(df_test, 
#                      method = c("center", "scale", "YeoJohnson"))
# transformed2 <- predict(pp_hpc2, newdata = df_test)
write.csv(df_test, "./fin_test.csv", row.names = F)

```

#--------------------------------------------
sub

```{r}
sample_sub = read.csv("./data/sub.csv")
out1 = read.csv("./out_lgbm.csv")
sample_sub$价格 = out1$X0
write.csv(sample_sub, "./data/sub1_lgbm.csv", row.names = F)
```

```{r}
library(tidyverse)
df_train %>% filter(df_train$X1 == 1)

.libPaths()
```

