---
title: "stg2_wm"
author: "Siming Yan"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
regresults <- read.csv("./ncaaw2-march-mania-2021/WRegularSeasonDetailedResults.csv")
results <- read.csv("./ncaaw2-march-mania-2021/WNCAATourneyDetailedResults.csv")
sub2 <- read.csv("./ncaaw2-march-mania-2021/WSampleSubmissionStage2.csv")
seeds <- read.csv("./ncaaw2-march-mania-2021/WNCAATourneySeeds.csv")
```


```{r cars}
seeds$Seed = as.numeric(substring(seeds$Seed,2,3))
### Collect regular season results - double the data by swapping team positions

r1 = regresults[, c("Season", "DayNum", "WTeamID", "WScore", "LTeamID", "LScore", "NumOT", "WFGA", "WAst", "WBlk", "LFGA", "LAst", "LBlk")]
r2 = regresults[, c("Season", "DayNum", "LTeamID", "LScore", "WTeamID", "WScore", "NumOT", "LFGA", "LAst", "LBlk", "WFGA", "WAst", "WBlk")]
names(r1) = c("Season", "DayNum", "T1", "T1_Points", "T2", "T2_Points", "NumOT", "T1_fga", "T1_ast", "T1_blk", "T2_fga", "T2_ast", "T2_blk")
names(r2) = c("Season", "DayNum", "T1", "T1_Points", "T2", "T2_Points", "NumOT", "T1_fga", "T1_ast", "T1_blk", "T2_fga", "T2_ast", "T2_blk")
regular_season = rbind(r1, r2)


### Collect tourney results - double the data by swapping team positions

t1 = results[, c("Season", "DayNum", "WTeamID", "LTeamID", "WScore", "LScore")] %>% mutate(ResultDiff = WScore - LScore)
t2 = results[, c("Season", "DayNum", "LTeamID", "WTeamID", "LScore", "WScore")] %>% mutate(ResultDiff = LScore - WScore)
names(t1) = c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff")
names(t2) = c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff")
tourney = rbind(t1, t2)


### Fit GLMM on regular season data (selected march madness teams only) - extract random effects for each team

march_teams = select(seeds, Season, Team = TeamID)
X =  regular_season %>% 
  inner_join(march_teams, by = c("Season" = "Season", "T1" = "Team")) %>% 
  inner_join(march_teams, by = c("Season" = "Season", "T2" = "Team")) %>% 
  select(Season, T1, T2, T1_Points, T2_Points, NumOT) %>% distinct()
X$T1 = as.factor(X$T1)
X$T2 = as.factor(X$T2)

quality = list()
for (season in unique(X$Season)) {
  glmm = 
    glmer(I(T1_Points > T2_Points) ~  (1 | T1) + (1 | T2), 
          data = X[X$Season == season & X$NumOT == 0, ], 
          family = binomial) 
  
  random_effects = ranef(glmm)$T1
  quality[[season]] = 
    data.frame(Season = season, 
               Team_Id = as.numeric(row.names(random_effects)), 
               quality = exp(random_effects[,"(Intercept)"]))
}
quality = do.call(rbind, quality)


### Regular season statistics

season_summary = 
  regular_season %>%
  mutate(win14days = ifelse(DayNum > 118 & T1_Points > T2_Points, 1, 0),
         last14days = ifelse(DayNum > 118, 1, 0)) %>% 
  group_by(Season, T1) %>%
  summarize(
    WinRatio14d = sum(win14days) / sum(last14days),
    PointsMean = mean(T1_Points),
    PointsMedian = median(T1_Points),
    PointsDiffMean = mean(T1_Points - T2_Points),
    FgaMean = mean(T1_fga), 
    FgaMedian = median(T1_fga),
    FgaMin = min(T1_fga), 
    FgaMax = max(T1_fga), 
    AstMean = mean(T1_ast), 
    BlkMean = mean(T1_blk), 
    OppFgaMean = mean(T2_fga), 
    OppFgaMin = min(T2_fga)  
  )

season_summary_X1 = season_summary
season_summary_X2 = season_summary
names(season_summary_X1) = c("Season", "T1", paste0("X1_",names(season_summary_X1)[-c(1,2)]))
names(season_summary_X2) = c("Season", "T2", paste0("X2_",names(season_summary_X2)[-c(1,2)]))


### Combine all features into a data frame

data_matrix =
  tourney %>% 
  left_join(season_summary_X1, by = c("Season", "T1")) %>% 
  left_join(season_summary_X2, by = c("Season", "T2")) %>%
  left_join(select(seeds, Season, T1 = TeamID, Seed1 = Seed), by = c("Season", "T1")) %>% 
  left_join(select(seeds, Season, T2 = TeamID, Seed2 = Seed), by = c("Season", "T2")) %>% 
  mutate(SeedDiff = Seed1 - Seed2) %>%
  left_join(select(quality, Season, T1 = Team_Id, quality_march_T1 = quality), by = c("Season", "T1")) %>%
  left_join(select(quality, Season, T2 = Team_Id, quality_march_T2 = quality), by = c("Season", "T2"))


### Prepare xgboost 
features = setdiff(names(data_matrix), c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff"))
```

```{r}
train_data_my  = data_matrix[, features]
train_label_my = data_matrix$ResultDiff

train_data_my

train_label_my = train_label_my %>% data.frame()
names(train_label_my) = "train_label_my"
train_label_my = train_label_my %>% mutate(train_label_my =ifelse(train_label_my > 0, 1, 0))
# train_label_my %>% table
train_label_my  = train_label_my$train_label_my %>% as.factor()
levels(train_label_my) = c("no", "yes")
# train_label_my
```

```{r}
trControl = trainControl(
    method = 'cv',
    number = 10,
    # summaryFunction = giniSummary,
    classProbs = TRUE,
    verboseIter = TRUE,
    allowParallel = TRUE)
```
 
```{r}
tuneGridXGB = expand.grid(
    nrounds = c(300),
    max_depth = c(4),
    eta = c(0.05),
    gamma = c(2),
    colsample_bytree = c(.6),
    subsample = c(0.750),
    min_child_weight = c(25))

xgbmod_2 <- train(
    x = train_data_my,
    y = train_label_my,
    method = 'xgbTree',
    metric = "Accuracy",
    # metric = 'NormalizedGini',
    trControl = trControl,
    tuneGrid = tuneGridXGB,
    verbose = T)

xgbmod_2
```

```{r}
sub2 <- read.csv("./ncaaw2-march-mania-2021/WSampleSubmissionStage2.csv")
sub2$Season = as.numeric(substring(sub2$ID,1,4))
sub2$T1 = as.numeric(substring(sub2$ID,6,9))
sub2$T2 = as.numeric(substring(sub2$ID,11,14))


Z2 = sub2 %>% 
  left_join(season_summary_X1, by = c("Season", "T1")) %>% 
  left_join(season_summary_X2, by = c("Season", "T2")) %>%
  left_join(select(seeds, Season, T1 = TeamID, Seed1 = Seed), by = c("Season", "T1")) %>% 
  left_join(select(seeds, Season, T2 = TeamID, Seed2 = Seed), by = c("Season", "T2")) %>% 
  mutate(SeedDiff = Seed1 - Seed2) %>%
  left_join(select(quality, Season, T1 = Team_Id, quality_march_T1 = quality), by = c("Season", "T1")) %>%
  left_join(select(quality, Season, T2 = Team_Id, quality_march_T2 = quality), by = c("Season", "T2"))

```

```{r}
test_my = Z2[, features]
# names(test_my)[!names(test_my) %in% names(train_data_my)]
# names(train_data_my)[!names(train_data_my) %in% names(test_my)]
test_my = test_my[, names(train_data_my)]
```

```{r}
preds <- predict(xgbmod_2, newdata = test_my, type = "prob")
sub2$Pred = preds$yes
sub2 = sub2[,1:2]
# sub2
write.csv(sub2, "./sub_stg2.csv", row.names = F)
```


```{r}
train_data_my_stg2 = cbind(train_data_my, train_label_my)
# train_label_my
write.csv(train_data_my_stg2 , "./sb/train_w_stg2.csv", row.names = F)
write.csv(test_my , "./sb/test_w_stg2.csv", row.names = F)
```

